"""empty message

Revision ID: 5d582ca1aac9
Revises: 4007ed05a184
Create Date: 2023-08-03 16:46:53.732420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d582ca1aac9'
down_revision = '4007ed05a184'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_slips', sa.Column('notified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_slips', 'notified_at')
    # ### end Alembic commands ###
