"""empty message

Revision ID: e07b0291e7e2
Revises: 
Create Date: 2023-08-02 09:21:48.939082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e07b0291e7e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_slips',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('government_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('debt_amount', sa.String(), nullable=False),
    sa.Column('debt_due_date', sa.Date(), nullable=True),
    sa.Column('debt_id', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('debt_id')
    )
    op.create_index(op.f('ix_bank_slips_id'), 'bank_slips', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_slips_id'), table_name='bank_slips')
    op.drop_table('bank_slips')
    # ### end Alembic commands ###
