"""empty message

Revision ID: e38659b34aad
Revises: f9ab032dd7e1
Create Date: 2023-08-02 18:20:46.060805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e38659b34aad'
down_revision = 'f9ab032dd7e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_slips', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.add_column('bank_slips', sa.Column('paid_amount', sa.String(), nullable=True))
    op.add_column('bank_slips', sa.Column('paid_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_slips', 'paid_by')
    op.drop_column('bank_slips', 'paid_amount')
    op.drop_column('bank_slips', 'paid_at')
    # ### end Alembic commands ###
