"""empty message

Revision ID: f9ab032dd7e1
Revises: fe81d97d5ae1
Create Date: 2023-08-02 18:19:28.196837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9ab032dd7e1'
down_revision = 'fe81d97d5ae1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
