"""empty message

Revision ID: fe81d97d5ae1
Revises: e07b0291e7e2
Create Date: 2023-08-02 09:50:04.214875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe81d97d5ae1'
down_revision = 'e07b0291e7e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bank_slips_debt_id_key', 'bank_slips', type_='unique')
    op.create_index(op.f('ix_bank_slips_debt_id'), 'bank_slips', ['debt_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_slips_debt_id'), table_name='bank_slips')
    op.create_unique_constraint('bank_slips_debt_id_key', 'bank_slips', ['debt_id'])
    # ### end Alembic commands ###
